- name: check aci-gw container image
  shell: docker inspect contiv/aci-gw
  register: docker_aci_inspect_result
  ignore_errors: yes
  run_once: true

- name: pull aci-gw container
  shell: docker pull contiv/aci-gw
  when: "'No such image' in docker_aci_inspect_result.stderr"
  run_once: true

- name: copy shell script for starting aci-gw
  template: src=aci_gw.j2 dest=/usr/bin/aci_gw.sh mode=u=rwx,g=rx,o=rx
  register: aci_env
  run_once: true

- name: copy systemd units for aci-gw
  copy: src=aci-gw.service dest=/etc/systemd/system/aci-gw.service
  register: aci_svc
  run_once: true

- name: reload daemon
  shell: systemctl daemon-reload
  when: aci_svc.changed or aci_env.changed

- name: start aci-gw container
  service: name=aci-gw state=started
  run_once: true

